name: Facebook Auto Share

on:
  schedule:
    - cron: "*/150 * * * *"   # her 150 dakikada (2.5 saat) çalışır
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run bot
      env:
        FB_COOKIES: ${{ secrets.FB_COOKIES }}
        FB_POST_URL: ${{ secrets.FB_POST_URL }}
        FB_GROUPS: ${{ secrets.FB_GROUPS }}
        FB_MESSAGE: ${{ secrets.FB_MESSAGE }}
      run: python bot.py
